twig:
    file_name_pattern: '*.twig'
#    form_themes: ['bootstrap_5_layout.html.twig']
    form_themes: ['extend_bootstrap/extend_bootstrap.html.twig']

when@test:
    twig:
        strict_variables: true
